services:
  web:
    build: ./c-sharp-playground-API
    depends_on:
      - rabbit
    ports:
      - "9028:9028"
    environment:
    - RabbitHost=rabbit
    - RabbitPort=5672
  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
#  postgres:
#    image: "postgres:9.4"
#    hostname: postgres
#    ports:
#      - "5432:5432"
