services:
  
  rabbit:
    image: "rabbitmq:3-management"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "15672:15672"
      - "5672:5672"
  # postgres:
  #   image: "postgres:9.4"
  #   hostname: postgres
  #   ports:
  #     - "5432:5432"
  web:
    build: ./c-sharp-playground-API
    depends_on:
      rabbit:
        condition: service_healthy
    ports:
      - "9028:9028"
    environment:
    - RabbitHost=rabbit
    - RabbitPort=5672